// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwyaeohfodhmiarddrdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eWFlb2hmb2RobWlhcmRkcmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzM3OTcsImV4cCI6MjA2NTU0OTc5N30.milxrOcBLL1WNzo4u9tMe3mm63lH-Zqgt7yJJ1LTMcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);